version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - HEXtoHSL
      - RGBtoHEX

  HEXtoHSL:
    image: hex2hsl
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.HEXtoRGB.rule=PathPrefix(`/HEXtoHSL`)"
      - "traefik.http.routers.HEXtoRGB.middlewares=HEXtoRGB-stripprefix"
      - "traefik.http.middlewares.HEXtoRGB-stripprefix.stripprefix.prefixes=/HEXtoRGB"
  
  RGBtoHEX:
    image: rgb2hex
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.HSLtoHEX.rule=PathPrefix(`/RGBtoHEX`)"
      - "traefik.http.routers.HSLtoHEX.middlewares=HSLtoHEX-stripprefix"
      - "traefik.http.middlewares.HSLtoHEX-stripprefix.stripprefix.prefixes=/HSLtoHEX"